# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-05 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_id', models.CharField(blank=True, max_length=32, verbose_name='Campaign Monitor ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('from_name', models.CharField(max_length=255, verbose_name='from name')),
                ('from_email', models.EmailField(max_length=254, verbose_name='email')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'draft'), (3, 'sent')], default=1, editable=False, verbose_name='status')),
                ('language', models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=15, verbose_name='language')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_id', models.CharField(blank=True, max_length=32, verbose_name='Campaign Monitor ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('unsubscribe_page', models.URLField(max_length=255, verbose_name='unsubscribe page')),
                ('confirmed_opt_in', models.BooleanField(default=True, verbose_name='confirmed opt-in')),
                ('confirmation_success_page', models.URLField(max_length=255, verbose_name='confirmation success page')),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
            },
        ),
        migrations.CreateModel(
            name='Recipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.CharField(blank=True, max_length=32, verbose_name='list')),
                ('segment_id', models.CharField(blank=True, editable=False, max_length=32, verbose_name='segment')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaignmonitor.Campaign', verbose_name='campaign')),
            ],
            options={
                'verbose_name': 'recipients',
                'verbose_name_plural': 'recipients',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=200, verbose_name='email address')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('state', models.PositiveIntegerField(choices=[(1, 'active'), (2, 'inactive')], verbose_name='state')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaignmonitor.List')),
            ],
            options={
                'verbose_name': 'subscriber',
                'verbose_name_plural': 'subscribers',
            },
        ),
        migrations.CreateModel(
            name='SubscriberCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=127, verbose_name='key')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='campaignmonitor.Subscriber', verbose_name='subscriber')),
            ],
            options={
                'verbose_name': 'custom field',
                'verbose_name_plural': 'custom fields',
            },
        ),
    ]
